server:
  port: 8083

spring:
  application:
    name: order-service

topic:
  name: order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka/