server:
  port: 8081

spring:
  application:
    name: account-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka/
